//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tellurian.Trains.MeetingApp.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class App {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tellurian.Trains.MeetingApp.Client.Resources.App", typeof(App).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All documentation available at.
        /// </summary>
        public static string AllDocumentationAvailableAt {
            get {
                return ResourceManager.GetString("AllDocumentationAvailableAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analogue.
        /// </summary>
        public static string Analogue {
            get {
                return ResourceManager.GetString("Analogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has stopped the clock!.
        /// </summary>
        public static string AnotherUserHasStoppedClock {
            get {
                return ResourceManager.GetString("AnotherUserHasStoppedClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply the settings that take effect immediately..
        /// </summary>
        public static string ApplyTooltip {
            get {
                return ResourceManager.GetString("ApplyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Fast Clock.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad request.
        /// </summary>
        public static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booster error.
        /// </summary>
        public static string BoosterError {
            get {
                return ResourceManager.GetString("BoosterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakfast.
        /// </summary>
        public static string Breakfast {
            get {
                return ResourceManager.GetString("Breakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop at fast time.
        /// </summary>
        public static string BreakTime {
            get {
                return ResourceManager.GetString("BreakTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabling error.
        /// </summary>
        public static string CablingError {
            get {
                return ResourceManager.GetString("CablingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in DCC central.
        /// </summary>
        public static string CentralError {
            get {
                return ResourceManager.GetString("CentralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change clock settings and then click Save to confirm new clock.
        /// </summary>
        public static string ChangeClockSettingsAndThenClickSaveToConfirmNewClock {
            get {
                return ResourceManager.GetString("ChangeClockSettingsAndThenClickSaveToConfirmNewClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock.
        /// </summary>
        public static string Clock {
            get {
                return ResourceManager.GetString("Clock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock Administration.
        /// </summary>
        public static string ClockAdministration {
            get {
                return ResourceManager.GetString("ClockAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock is running in real time.
        /// </summary>
        public static string ClockIsRunningInRealTime {
            get {
                return ResourceManager.GetString("ClockIsRunningInRealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock password.
        /// </summary>
        public static string ClockPassword {
            get {
                return ResourceManager.GetString("ClockPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock settings.
        /// </summary>
        public static string ClockSettings {
            get {
                return ResourceManager.GetString("ClockSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock speed {0:F1}.
        /// </summary>
        public static string ClockSpeed {
            get {
                return ResourceManager.GetString("ClockSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock users.
        /// </summary>
        public static string ClockUsers {
            get {
                return ResourceManager.GetString("ClockUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The clock was created.
        /// </summary>
        public static string ClockWasCreated {
            get {
                return ResourceManager.GetString("ClockWasCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The clock was restarted.
        /// </summary>
        public static string ClockWasRestarted {
            get {
                return ResourceManager.GetString("ClockWasRestarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The clock was started.
        /// </summary>
        public static string ClockWasStarted {
            get {
                return ResourceManager.GetString("ClockWasStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The clock was stopped.
        /// </summary>
        public static string ClockWasStopped {
            get {
                return ResourceManager.GetString("ClockWasStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee break.
        /// </summary>
        public static string CoffeBreak {
            get {
                return ResourceManager.GetString("CoffeBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict.
        /// </summary>
        public static string Conflict {
            get {
                return ResourceManager.GetString("Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue session from this time.
        /// </summary>
        public static string ContinueGameFromThisTime {
            get {
                return ResourceManager.GetString("ContinueGameFromThisTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new clock.
        /// </summary>
        public static string CreateNewClock {
            get {
                return ResourceManager.GetString("CreateNewClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fills the form with a new random clock name and random passwords..
        /// </summary>
        public static string CreateNewClockTooltip {
            get {
                return ResourceManager.GetString("CreateNewClockTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current clock name: {0}.
        /// </summary>
        public static string CurrentClockName {
            get {
                return ResourceManager.GetString("CurrentClockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current {0} clock users.
        /// </summary>
        public static string CurrentClockUsers {
            get {
                return ResourceManager.GetString("CurrentClockUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delays, keep driving until you catch up.
        /// </summary>
        public static string Delays {
            get {
                return ResourceManager.GetString("Delays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derailment.
        /// </summary>
        public static string Derailment {
            get {
                return ResourceManager.GetString("Derailment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital.
        /// </summary>
        public static string Digital {
            get {
                return ResourceManager.GetString("Digital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner.
        /// </summary>
        public static string Dinner {
            get {
                return ResourceManager.GetString("Dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display time maximized.
        /// </summary>
        public static string DisplayTimeMaximized {
            get {
                return ResourceManager.GetString("DisplayTimeMaximized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done for today.
        /// </summary>
        public static string DoneForToday {
            get {
                return ResourceManager.GetString("DoneForToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver shortage, continue driving.
        /// </summary>
        public static string DriverShortage {
            get {
                return ResourceManager.GetString("DriverShortage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected resume time.
        /// </summary>
        public static string ExpectedResumeTime {
            get {
                return ResourceManager.GetString("ExpectedResumeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast clock.
        /// </summary>
        public static string Fastclock {
            get {
                return ResourceManager.GetString("Fastclock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session duration (hours).
        /// </summary>
        public static string GameDuration {
            get {
                return ResourceManager.GetString("GameDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session ends at {0}, real time {1}.
        /// </summary>
        public static string GameEndsAtTime {
            get {
                return ResourceManager.GetString("GameEndsAtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session hour is {0:F0} min.
        /// </summary>
        public static string GameHourIsMinutes {
            get {
                return ResourceManager.GetString("GameHourIsMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session is paused.
        /// </summary>
        public static string GameIsPaused {
            get {
                return ResourceManager.GetString("GameIsPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session is paused for.
        /// </summary>
        public static string GameIsPausedFor {
            get {
                return ResourceManager.GetString("GameIsPausedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session start time.
        /// </summary>
        public static string GameStartTime {
            get {
                return ResourceManager.GetString("GameStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get clock app.
        /// </summary>
        public static string GetClock {
            get {
                return ResourceManager.GetString("GetClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall is closing.
        /// </summary>
        public static string HallIsClosing {
            get {
                return ResourceManager.GetString("HallIsClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid settings.
        /// </summary>
        public static string InvalidSettings {
            get {
                return ResourceManager.GetString("InvalidSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP-address.
        /// </summary>
        public static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock is running.
        /// </summary>
        public static string IsRunning {
            get {
                return ResourceManager.GetString("IsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest access time.
        /// </summary>
        public static string LatestAccessTime {
            get {
                return ResourceManager.GetString("LatestAccessTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocoNet error.
        /// </summary>
        public static string LocoNetError {
            get {
                return ResourceManager.GetString("LocoNetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch.
        /// </summary>
        public static string Lunch {
            get {
                return ResourceManager.GetString("Lunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting.
        /// </summary>
        public static string Meeting {
            get {
                return ResourceManager.GetString("Meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No day.
        /// </summary>
        public static string NoDay {
            get {
                return ResourceManager.GetString("NoDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no reason.
        /// </summary>
        public static string NoReason {
            get {
                return ResourceManager.GetString("NoReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authorized.
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note!.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not executed.
        /// </summary>
        public static string NotExecuted {
            get {
                return ResourceManager.GetString("NotExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there&apos;s nothing at this address!.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users or you are not authorised..
        /// </summary>
        public static string NoUsersOrUnathorized {
            get {
                return ResourceManager.GetString("NoUsersOrUnathorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only administrator can restart.
        /// </summary>
        public static string OnlyAdministratorCanStart {
            get {
                return ResourceManager.GetString("OnlyAdministratorCanStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other reason.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause at real time.
        /// </summary>
        public static string PauseAtRealTime {
            get {
                return ResourceManager.GetString("PauseAtRealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause from {0} for {1}..
        /// </summary>
        public static string PauseAtTimeForReason {
            get {
                return ResourceManager.GetString("PauseAtTimeForReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause between {0} and {1} for {2}..
        /// </summary>
        public static string PauseBetweenTimeForReason {
            get {
                return ResourceManager.GetString("PauseBetweenTimeForReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point problem.
        /// </summary>
        public static string PointProblem {
            get {
                return ResourceManager.GetString("PointProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real time clock.
        /// </summary>
        public static string Realclock {
            get {
                return ResourceManager.GetString("Realclock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        public static string References {
            get {
                return ResourceManager.GetString("References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshes the form with actual settings from server..
        /// </summary>
        public static string RefreshTooltip {
            get {
                return ResourceManager.GetString("RefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register name and clock password to modify clock settings.
        /// </summary>
        public static string RegisterNameAndPassword {
            get {
                return ResourceManager.GetString("RegisterNameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register name and password to be able to stop clock..
        /// </summary>
        public static string RegisterNameAndPasswordForStoppingClock {
            get {
                return ResourceManager.GetString("RegisterNameAndPasswordForStoppingClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets the clock to the session&apos;s start time..
        /// </summary>
        public static string ResetTooltip {
            get {
                return ResourceManager.GetString("ResetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select clock.
        /// </summary>
        public static string SelectClock {
            get {
                return ResourceManager.GetString("SelectClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select clock and more settings.
        /// </summary>
        public static string SelectClockAndMoreSettings {
            get {
                return ResourceManager.GetString("SelectClockAndMoreSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select clock mode.
        /// </summary>
        public static string SelectClockMode {
            get {
                return ResourceManager.GetString("SelectClockMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select display mode.
        /// </summary>
        public static string SelectDisplay {
            get {
                return ResourceManager.GetString("SelectDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select stop reason.
        /// </summary>
        public static string SelectStopReason {
            get {
                return ResourceManager.GetString("SelectStopReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select colour theme.
        /// </summary>
        public static string SelectTheme {
            get {
                return ResourceManager.GetString("SelectTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session pause.
        /// </summary>
        public static string SessionBreak {
            get {
                return ResourceManager.GetString("SessionBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session has ended!.
        /// </summary>
        public static string SessionEnded {
            get {
                return ResourceManager.GetString("SessionEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session interrupts at {0}.
        /// </summary>
        public static string SessionInterruptsAtTime {
            get {
                return ResourceManager.GetString("SessionInterruptsAtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session is resumed at {0}.
        /// </summary>
        public static string SessionIsResumedAtTime {
            get {
                return ResourceManager.GetString("SessionIsResumedAtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set password for administrators.
        /// </summary>
        public static string SetClockAdministratorPassword {
            get {
                return ResourceManager.GetString("SetClockAdministratorPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set clock name.
        /// </summary>
        public static string SetClockName {
            get {
                return ResourceManager.GetString("SetClockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set password for users.
        /// </summary>
        public static string SetClockUserPassword {
            get {
                return ResourceManager.GetString("SetClockUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show less.
        /// </summary>
        public static string ShowLess {
            get {
                return ResourceManager.GetString("ShowLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more.
        /// </summary>
        public static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show real time when paused.
        /// </summary>
        public static string ShowRealTimeWhenPaused {
            get {
                return ResourceManager.GetString("ShowRealTimeWhenPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show seconds hand.
        /// </summary>
        public static string ShowSecondsHand {
            get {
                return ResourceManager.GetString("ShowSecondsHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock speed.
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts the clock..
        /// </summary>
        public static string StartTooltip {
            get {
                return ResourceManager.GetString("StartTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with station control system.
        /// </summary>
        public static string StationControl {
            get {
                return ResourceManager.GetString("StationControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station- or personal name.
        /// </summary>
        public static string StationOrPersonalName {
            get {
                return ResourceManager.GetString("StationOrPersonalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped by {0}.
        /// </summary>
        public static string StoppedByUser {
            get {
                return ResourceManager.GetString("StoppedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop reason.
        /// </summary>
        public static string StopReason {
            get {
                return ResourceManager.GetString("StopReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stops at {0}: {1}..
        /// </summary>
        public static string StopsAtTimeForReason {
            get {
                return ResourceManager.GetString("StopsAtTimeForReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stops the clock without a specific reason given..
        /// </summary>
        public static string StopTooltip {
            get {
                return ResourceManager.GetString("StopTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You changed theme. Please, reload app for theme to take effect..
        /// </summary>
        public static string ThemeHasChangedPleaseReloadApp {
            get {
                return ResourceManager.GetString("ThemeHasChangedPleaseReloadApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track problem.
        /// </summary>
        public static string TrackProblem {
            get {
                return ResourceManager.GetString("TrackProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        public static string UserHasStoppedOfReason {
            get {
                return ResourceManager.GetString("UserHasStoppedOfReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username &apos;{0}&apos; is already taken..
        /// </summary>
        public static string UsernameIsAlreadyTaken {
            get {
                return ResourceManager.GetString("UsernameIsAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle breakdown.
        /// </summary>
        public static string VehicleBreakdown {
            get {
                return ResourceManager.GetString("VehicleBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle shortage.
        /// </summary>
        public static string VehicleShortage {
            get {
                return ResourceManager.GetString("VehicleShortage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for better times!.
        /// </summary>
        public static string WaitingForBetterTimes {
            get {
                return ResourceManager.GetString("WaitingForBetterTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for data....
        /// </summary>
        public static string WaitingForData {
            get {
                return ResourceManager.GetString("WaitingForData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session weekday.
        /// </summary>
        public static string Weekday {
            get {
                return ResourceManager.GetString("Weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}.
        /// </summary>
        public static string WelcomeUser {
            get {
                return ResourceManager.GetString("WelcomeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not permitted to start the clock..
        /// </summary>
        public static string YouAreNotAuthorizedToStartTheClock {
            get {
                return ResourceManager.GetString("YouAreNotAuthorizedToStartTheClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not permitted to stop the clock..
        /// </summary>
        public static string YouAreNotAuthorizedToStopTheClock {
            get {
                return ResourceManager.GetString("YouAreNotAuthorizedToStopTheClock", resourceCulture);
            }
        }
    }
}
